Add a new user during manual order creation in EDD 3.0
awesomemotive/edd-auto-register pull request #88
Opened 2022-02-17 13:23 UTC by robincornett

Fixes #37
Branched from #33 due to parameter changes.

Proposed Changes:
1. Hooks into `edd_transition_order_status`, which happens in EDD 3.0 when an order status is changed.
2. Checks if the `edd_add_order` hook fired (only runs for manual orders) and whether the new order status is complete. If so, then it registers a new user.

2022-03-04 05:16 UTC, cklosowski requested changes

2022-03-04 05:16 UTC, cklosowski commented on edd-auto-register.php
> +			if ( ! did_action( 'edd_add_order' ) && 'complete' !== $new_status ) {
This seems kind of 'hacky' and could be prone to firing when it shouldn't be in the future if someone 'forgets' about this.

Since EDD 3.0 isn't live, we could very easily add a hook once an order is manually added to handle this process.

2022-03-08 19:38 UTC, robincornett commented
PR updated to use the new hook introduced in https://github.com/awesomemotive/easy-digital-downloads/issues/9105 (note: don't merge this until that's finalized).

2022-04-13 22:49 UTC, cklosowski approved these changes

2022-04-13 22:50 UTC, merged